# Generated by Django 4.1.7 on 2023-03-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallary',
        ),
    ]
