# Generated by Django 4.1.7 on 2023-03-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_gallery_gallary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='gallary',
            options={'verbose_name_plural': 'Gallaries'},
        ),
    ]
