# Generated by Django 4.1.7 on 2023-03-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_faculty_options_alter_gallary_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnonymosContact',
            new_name='AnonymousContact',
        ),
    ]
