# Generated by Django 4.1.7 on 2023-03-30 18:06

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_anonymoscontact_anonymouscontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallary',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='GallaryItem',
            new_name='GalleryItem',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
