# Generated by Django 4.1.7 on 2023-03-30 18:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_gallary_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=django_quill.fields.QuillField(),
        ),
    ]
