# Generated by Django 4.1.7 on 2023-03-31 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_newspost_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectorcontact',
            name='contact_type',
            field=models.CharField(choices=[('Murojaat', 'm'), ('Shikoyat', 'sh'), ('Taklif', 't')], default=datetime.datetime(2023, 3, 31, 1, 43, 14, 603958, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
