# Generated by Django 4.1.7 on 2023-03-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rectorcontact_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media/useful_resources')),
                ('link', models.URLField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Useful Resources',
            },
        ),
    ]
