# Generated by Django 4.1.7 on 2023-03-31 07:41

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_usefulresources'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='media/talented_students')),
                ('phone_number', models.CharField(max_length=255)),
                ('biography', django_quill.fields.QuillField()),
            ],
            options={
                'verbose_name_plural': 'Talented Students',
            },
        ),
        migrations.AddField(
            model_name='newspost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/news_post/'),
        ),
        migrations.AlterField(
            model_name='rectorcontact',
            name='contact_type',
            field=models.CharField(choices=[('m', 'Murojaat'), ('sh', 'Shikoyat'), ('t', 'Taklif')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rectorcontact',
            name='status',
            field=models.CharField(choices=[('js', 'Jismoniy shaxs'), ('ys', 'Yuridik shaxs')], max_length=255),
        ),
    ]
