# Generated by Django 4.1.7 on 2023-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_talentedstudent_newspost_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulresources',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/useful_resources'),
        ),
    ]
