# Generated by Django 4.1.7 on 2023-04-01 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_usefulresources_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 1, 5, 53, 40, 813222, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
