# Generated by Django 4.1.7 on 2023-04-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newspost_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentedstudent',
            old_name='name',
            new_name='fullname',
        ),
    ]
