# Generated by Django 4.1.7 on 2023-04-02 04:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_name_talentedstudent_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('grid-item--width2', 'uzunlik 2'), ('grid-item--width3', 'uzunlik 3'), ('grid-item--height2', 'balandlik 2'), ('grid-item--height3', 'balandlik 3')], max_length=255, null=True),
        ),
    ]
